theme: jekyll-theme-minimal
title: "root@33b5e5 #"
name: 33b5e5
description: SysAdmin, Musician, Hacker of Things
baseurl: ""
url: https://33b5e5.com
email: 33b5e5@protonmail.com
twitter_username: 33b5e5
github_username: 33b5e5
show_downloads: false
