theme: jekyll-theme-slate
title: [33b5e5@localhost]#
name: Ryan Rhea
description: SysAdmin, Musician, Hacker
baseurl: ""
url: https://33b5e5.github.io
email: 33b5e5@protonmail.com
twitter_username: 33b5e5
github_username: 33b5e5
show_downloads: false
