theme: jekyll-theme-minimal
title: "33b5e5.com"
name: "33b5e5"
description: "Building apps at http://meridianapps.com . Playing music. Hacking things. Shouting into the ether."
baseurl: ""
url: https://33b5e5.com
email: 33b5e5@protonmail.com
twitter_username: 33b5e5
github_username: 33b5e5
show_downloads: false
