theme: jekyll-theme-hacker
name: Ryan Rhea
description: SysAdmin, Musician, Hacker
avatar: https://raw.githubusercontent.com/33b5e5/33b5e5.github.io/master/images/avatar.png
url: https://33b5e5.github.io
